// src/lib/mockData.ts

import { assessTriage } from './triage'
import type { Asset, Household } from '@/types'

export const mockHouseholds: Household[] = [
  {
    id: 'HH-MOCK1',
    lat: 10.6725, lng: 122.9589,
    barangay: 'Singcang-Airport', purok: 'Purok 1',
    street: '12 Magsaysay Ave', structure: 'Single-story',
    head: 'Maria Santos', contact: '0917-123-4567', occupants: 4,
    vulnArr: ['Bedridden', 'Senior'],
    notes: 'Stroke patient, 2nd floor flooded.',
    status: 'Pending',
    triage: assessTriage(['Bedridden', 'Senior']),
  },
  {
    id: 'HH-MOCK2',
    lat: 10.6780, lng: 122.9490,
    barangay: 'Mansilingan', purok: 'Riverside',
    street: 'Blk 4 Lot 12', structure: 'Light materials',
    head: 'Juan Dela Cruz', contact: '0919-987-6543', occupants: 6,
    vulnArr: ['Infant', 'Pregnant'],
    notes: 'Wife is 8 months pregnant.',
    status: 'Pending',
    triage: assessTriage(['Infant', 'Pregnant']),
  },
  {
    id: 'HH-MOCK3',
    lat: 10.6690, lng: 122.9610,
    barangay: 'Taculing', purok: 'Rosario',
    street: '99 Gonzaga St', structure: 'Multi-story',
    head: 'Elena Gomez', contact: '0922-333-4444', occupants: 2,
    vulnArr: ['Wheelchair'],
    notes: 'Trapped on 1st floor.',
    status: 'Pending',
    triage: assessTriage(['Wheelchair']),
  },
  {
    id: 'HH-MOCK4',
    lat: 10.6850, lng: 122.9750,
    barangay: 'Estefania', purok: 'San Dionisio',
    street: '15 Burgos Ext', structure: 'Single-story',
    head: 'Ricardo Dalisay', contact: '0933-555-7777', occupants: 3,
    vulnArr: ['Oxygen', 'PWD'],
    notes: 'Requires constant power for oxygen concentrator.',
    status: 'Pending',
    triage: assessTriage(['Oxygen', 'PWD']),
  },
  {
    id: 'HH-MOCK5',
    lat: 10.6710, lng: 122.9650,
    barangay: 'Villamonte', purok: 'Malipayon',
    street: '42 Lopez Jaena', structure: 'Multi-story',
    head: 'Teresa Pineda', contact: '0945-888-1111', occupants: 5,
    vulnArr: ['Senior'],
    notes: 'Safely evacuated.',
    status: 'Rescued',
    triage: assessTriage(['Senior']),
  },
  {
    id: 'HH-MOCK6',
    lat: 10.7000, lng: 122.9550,
    barangay: 'Bata', purok: 'Magsungay',
    street: '88 Lacson St', structure: 'Light materials',
    head: 'Arturo Macapagal', contact: '0915-222-3333', occupants: 4,
    vulnArr: ['Bedridden', 'Dialysis'],
    notes: 'Needs immediate medical transport.',
    status: 'Pending',
    triage: assessTriage(['Bedridden', 'Dialysis']),
  },
  {
    id: 'HH-MOCK7',
    lat: 10.6600, lng: 122.9450,
    barangay: 'Singcang-Airport', purok: 'Airport Subd',
    street: '2A Terminal Way', structure: 'Single-story',
    head: 'Lina Alcantara', contact: '0999-111-9999', occupants: 7,
    vulnArr: ['Infant', 'Senior'],
    notes: 'Trapped with 2-month old twins and grandmother.',
    status: 'Pending',
    triage: assessTriage(['Infant', 'Senior']),
  },
  {
    id: 'HH-MOCK8',
    lat: 10.6550, lng: 122.9700,
    barangay: 'Mansilingan', purok: 'Pag-asa',
    street: 'Blk 9 L 24', structure: 'Light materials',
    head: 'Fernando Reyes', contact: '0917-888-2222', occupants: 3,
    vulnArr: ['Dialysis', 'Wheelchair'],
    notes: 'Missed dialysis session, water rising rapidly.',
    status: 'Pending',
    triage: assessTriage(['Dialysis', 'Wheelchair']),
  },
]

export const mockAssets: Asset[] = [
  {
    id: 'A1', name: 'Rescue Boat Alpha', type: 'Boat',
    unit: 'BFP Marine', status: 'Active',
    lat: 10.6650, lng: 122.9450, icon: '🚤',
  },
  {
    id: 'A2', name: 'Transport Truck 01', type: 'Truck',
    unit: 'Army 303rd', status: 'Dispatching',
    lat: 10.6800, lng: 122.9600, icon: '🛻',
  },
  {
    id: 'A3', name: 'Medic Team Bravo', type: 'Ambulance',
    unit: 'Red Cross', status: 'Active',
    lat: 10.6720, lng: 122.9550, icon: '🚑',
  },
]
